import Providers from "@/app/Providers";
import estedadFont from "../../../constant/localFonts";
import { Toaster } from "react-hot-toast";
import "../../globals.css";
import Sidebar from "./Sidebar";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body
        suppressHydrationWarning={true}
        className={`${estedadFont.variable} bg-white`}
      >
        <Providers>
          <Toaster />
          <div className="grid grid-cols-4 grid-rows-5 gap-4 min-h-screen   px-4">
            <div className="md:row-span-5 md:col-span-1 col-span-4 bg-white p-4 rounded-lg shadow-sm">
              <Sidebar />
            </div>

            <div className="md:col-span-3 col-span-4 row-span-5 mt-3 shadow-sm shadow-gray-400  bg-[#F8F8FA]  rounded-xl">
              {children}
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
